#!/bin/bash

## PARSE ARGUMENTS
port=8080 #defualt

while [[ $# -gt 0 ]]
do
  key="${1}"

  case ${key} in
  -p|--port)
    port="${2}"
    shift 2
    ;;
  -d|--dir)
    dir="${2}"
    shift 2
    ;;
  *)    # unknown option
    shift # past argument
    ;;
  esac
done

if [ -z "$dir" ]; then
  echo 'Missing -d, i.e., directory' >&2
  exit 1
fi

root=$HOME/repos/QualCmp
data=$root/imgs
path=$(pwd)/$dir

if [ ! -d $path ]; then
  echo 'No such a directory $path' >&2
  exit 1
fi

# CHANGE DIRECTORY 
cd $root
# CREATE SYMBOLIC LINK
rm $data > /dev/null
ln -sf $path $data
# CREATE CONFIGURATION FILE
python gen_config.py
# EXECUTE SERVER
python server.py --port $port
